In [25]:
import pandas as pd
import numpy as np

In [26]:
df_2024_1 = pd.read_csv ('Preços semestrais - AUTOMOTIVOS_2024.01.csv', sep=';', decimal= ',')
df_2024_2 = pd.read_csv ('Preços semestrais - AUTOMOTIVOS_2024.02.csv', sep=';', decimal= ',')
df_2025_1 = pd.read_csv ('Preços semestrais - AUTOMOTIVOS_2025.01.csv', sep=';', decimal= ',')
df_2025_2 = pd.read_csv ('Preços semestrais - AUTOMOTIVOS_2025.02.csv', sep=';', decimal= ',')

C:\Users\eduar\AppData\Local\Temp\ipykernel_15480\1461245115.py:3: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_1 = pd.read_csv ('Preços semestrais - AUTOMOTIVOS_2025.01.csv', sep=';', decimal= ',')

In [ ]:
df = pd.concat([df_2024_1, df_2024_2, df_2025_1, df_2025_2], ignore_index=True)
print (df.shape) 
display (df.head())

In [ ]:
df.info()

In [27]:
print(df.columns)

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='str')

In [ ]:
TESTE = df ['Municipio'].value_counts().reset_index() #para verificar o que há dentro da coluna, nesse caso produto
TESTE

In [ ]:
df.tail(3)

In [ ]:
df_gasolina = df.loc[(df['Estado - Sigla'] == 'RJ') & (df['Produto'] == 'GASOLINA')]
df_gasolina

df_prod = ['GASOLINA']

df_rj = df.loc[df['Produto'].isin(df_prod) & (df['Estado - Sigla'] == 'RJ')]
df_rj

In [9]:
df_gasolina_comum_rj = df_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_gasolina_comum_rj

                      Municipio  Valor de Venda
29                    TRES RIOS        6.591634
0                ANGRA DOS REIS        6.521620
18                   PETROPOLIS        6.479639
2                BARRA DO PIRAI        6.375640
11                        MACAE        6.364828
16                NOVA FRIBURGO        6.357044
10                    ITAPERUNA        6.352013
6         CAMPOS DOS GOYTACAZES        6.338306
5                     CABO FRIO        6.322089
23  SAO FRANCISCO DE ITABAPOANA        6.214804
31                VOLTA REDONDA        6.206265
1                      ARARUAMA        6.158700
27                    SAQUAREMA        6.133649
3                   BARRA MANSA        6.092928
30                      VALENCA        6.047609
26                     SAPUCAIA        5.994565
22       SANTO ANTONIO DE PADUA        5.962665
21               RIO DE JANEIRO        5.930698
13                       MARICA        5.899534
19                      RESENDE        5.885842
24                  SAO GONCALO        5.855353
20                   RIO BONITO        5.848639
8                      ITABORAI        5.842281
17                  NOVA IGUACU        5.807970
7               DUQUE DE CAXIAS        5.793860
25           SAO JOAO DE MERITI        5.780650
14                    NILOPOLIS        5.769526
15                      NITEROI        5.757424
4                  BELFORD ROXO        5.752965
12                         MAGE        5.615435
9                       ITAGUAI        5.602390
28                  TERESOPOLIS        5.508448

In [30]:
df_gasolina_comum_rj_posto = df_rj.groupby('Revenda')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_gasolina_comum_rj_posto

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000
776                        POSTO SATURNO FRIBURGO LTDA        6.824444
1                   A C TRANCOZO M B COMBUSTIVEIS LTDA        6.742157
304  COMERCIO DE PETROLEO E DERIVADOS COND DO RIO N...        6.713529
..                                                 ...             ...
668                             POSTO FLAMAREDI EIRELI        5.282000
571              POSTO DE GASOLINA JARDIM SULACAP LTDA        5.226364
569              POSTO DE GASOLINA JAGUAR DO ANIL LTDA        5.156667
560                        POSTO DE GASOLINA GALP LTDA        5.090000
567                     POSTO DE GASOLINA ITAJUBA LTDA        5.090000

[872 rows x 2 columns]

In [ ]:
array_gas_comum_rj = np.array(df_gasolina_comum_rj_posto['Valor de Venda'])
array_gas_comum_rj

In [12]:
media = np.mean(array_gas_comum_rj)
mediana = np.median(array_gas_comum_rj)
q1 = np.percentile(array_gas_comum_rj, 25)
q3 = np.percentile(array_gas_comum_rj,75)
iqr = q3 - q1
limite_superior = q3 + (1.5 * iqr)
limite_inferior = q1 - (1.5 * iqr)
distancia = (media - mediana) / mediana

print (f'Média {media}')
print (f'Mediana {mediana}')
print (f'Distancia {distancia:.2%}')
print (f'Q1 {q1}')
print (f'Q3 {q3}')
print(f'Limite Superior {limite_superior}')
print(f'Limite Inferior {limite_inferior}')

Média 5.947818265606212
Mediana 5.9136419461502125
Distancia 0.58%
Q1 5.692154135338346
Q3 6.19
Limite Superior 6.936768796992482
Limite Inferior 4.945385338345865

In [13]:
outlier_sup_preco = df_gasolina_comum_rj_posto.loc[df_gasolina_comum_rj_posto['Valor de Venda'] > limite_superior]

outlier_sup_preco

                                               Revenda  Valor de Venda
690                        POSTO JARDIM OCEANICO LTDA.        7.750674
76   AUTO POSTO DE COMBUSTIVEIS M C 2000 DE SANTA I...        7.415000

In [14]:
outlier_inf_preco = df_gasolina_comum_rj_posto.loc[df_gasolina_comum_rj_posto['Valor de Venda'] < limite_inferior]

outlier_inf_preco

Empty DataFrame
Columns: [Revenda, Valor de Venda]
Index: []

In [ ]:
df_est = ['RJ','SP']
df_eta = df.loc[df['Estado - Sigla'].isin(df_est) & (df['Produto'] == 'ETANOL')]
df_eta

In [ ]:
df_RJ_etanol = df.loc[(df['Estado - Sigla'] == 'RJ') & (df['Produto'] == 'ETANOL')]
df_RJ_etanol

In [ ]:
df_etanol_rj = df_RJ_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_etanol_rj

In [ ]:
array_etanol_rj = np.array(df_etanol_rj['Valor de Venda'])
array_etanol_rj

In [89]:
media_rj = np.mean(array_etanol_rj)
mediana_rj = np.median(array_etanol_rj)
q1_rj = np.percentile(array_etanol_rj, 25)
q3_rj = np.percentile(array_etanol_rj,75)
iqr = q3_rj - q1_rj
limite_superior_rj = q3_rj + (1.5 * iqr)
limite_inferior_rj = q1_rj - (1.5 * iqr)
distancia = (media_rj - mediana_rj) / mediana_rj

print (f'Média {media_rj}')
print (f'Mediana {mediana_rj}')
print (f'Distancia {distancia:.2%}')
print (f'Q1 {q1_rj}')
print (f'Q3 {q3_rj}')
print(f'Limite Superior {limite_superior_rj}')
print(f'Limite Inferior {limite_inferior_rj}')

Média 4.446460031915704
Mediana 4.407249773866983
Distancia 0.89%
Q1 4.27764986189478
Q3 4.558372256933862
Limite Superior 4.979455849492485
Limite Inferior 3.8565662693361564

In [ ]:
df_SP_etanol = df.loc[(df['Estado - Sigla'] == 'SP') & (df['Produto'] == 'ETANOL')]
df_SP_etanol

In [ ]:
df_etanol_sp = df_SP_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_etanol_sp

In [ ]:
array_etanol_sp = np.array(df_etanol_sp['Valor de Venda'])
array_etanol_sp

In [ ]:
media_sp = np.mean(array_etanol_sp)
mediana_sp = np.median(array_etanol_sp)
q1_sp = np.percentile(array_etanol_sp, 25)
q3_sp = np.percentile(array_etanol_sp,75)
iqr = q3_sp - q1_sp
limite_superior_sp = q3_sp + (1.5 * iqr)
limite_inferior_sp = q1_sp - (1.5 * iqr)
distancia_sp = (media_sp - mediana_sp) / mediana_sp

print (f'Média SP {media_sp}')
print (f'Mediana SP {mediana_sp}')
print (f'Distancia {distancia_sp:.2%}')
print (f'Q1 {q1_sp}')
print (f'Q3 {q3_sp}')
print(f'Limite Superior {limite_superior_sp}')
print(f'Limite Inferior {limite_inferior_sp}')

In [ ]:

print (f'Média do etanol RJ {media_rj}\nMédia do etanol SP {media_sp}')

print(f'Maior preço RJ\n {df_etanol_rj.max()}')
print(f'Menor preço RJ\n {df_etanol_rj.min()}')

print(f'Maior preço SP\n {df_etanol_sp.max()}')
print(f'Menor preço SP\n {df_etanol_sp.min()}')

In [ ]:
outlier_sup_preco_rj_eta = df_etanol_rj.loc[df_etanol_rj['Valor de Venda'] > limite_superior_rj]

outlier_sup_preco_rj_eta

In [ ]:
outlier_inf_preco_rj_eta = df_etanol_rj.loc[df_etanol_rj['Valor de Venda'] < limite_inferior_rj]

outlier_inf_preco_rj_eta

In [86]:
outlier_sup_preco_sp_eta = df_etanol_sp.loc[df_etanol_sp['Valor de Venda'] > limite_superior_sp]

outlier_sup_preco_sp_eta

   Municipio  Valor de Venda
10   BARUERI        4.437937
24   CUBATAO        4.394575
31   GUARUJA        4.329950

In [ ]:
outlier_inf_preco_sp_eta = df_etanol_sp.loc[df_etanol_sp['Valor de Venda'] < limite_inferior_sp]

outlier_inf_preco_sp_eta

In [ ]:
df_gasosa = df.loc[(df['Municipio'] == 'RIO DE JANEIRO') & (df['Produto'] == 'GASOLINA')]
df_gasosa

In [ ]:
df_gasolina_bairro_rj = df_gasosa.groupby('Bairro')['Valor de Venda'].mean().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_gasolina_bairro_rj

In [ ]:
array_bairro = np.array(df_gasolina_bairro_rj['Valor de Venda'])
array_bairro

In [118]:
media_br = np.mean (array_bairro)
mediana_br = np.median (array_bairro)
q1_br = np.percentile(array_bairro, 25)
q3_br = np.percentile(array_bairro,75)
iqr_br = q3_br - q1_br
limite_superior_br = q3_br + (1.5 * iqr_br)
limite_inferior_br = q1_br - (1.5 * iqr_br)
distancia_br = (media_br - mediana_br) / mediana_br

print (f'Média {media_br}')
print (f'Mediana {mediana_br}')
print (f'Distancia {distancia_br:.2%}')
print (f'Q1 {q1_br}')
print (f'Q3 {q3_br}')
print(f'Limite Superior {limite_superior_br}')
print(f'Limite Inferior {limite_inferior_br}')

Média 5.854678797322661
Mediana 5.8434
Distancia 0.19%
Q1 5.640000000000001
Q3 6.060588235294118
Limite Superior 6.691470588235293
Limite Inferior 5.009117647058825

In [119]:
outlier_sup_bairro = df_gasolina_bairro_rj.loc[df_gasolina_bairro_rj['Valor de Venda'] > limite_superior_br]
outlier_sup_bairro

      Bairro  Valor de Venda
23  FLAMENGO        6.696667

In [120]:
outlier_inf_bairro = df_gasolina_bairro_rj.loc[df_gasolina_bairro_rj['Valor de Venda'] < limite_inferior_br]
outlier_inf_bairro

Empty DataFrame
Columns: [Bairro, Valor de Venda]
Index: []