In [17]:
import pandas as pd
import numpy as np

In [18]:
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(url, encoding= 'latin1', sep=';')
df.head(3)

KeyboardInterrupt

In [ ]:
df.tail(2)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37997,167,6,2026,2026m06,43,5,Paraty,3303807,Interior,1,...,4.0,0.0,14,1,1,0,0,0,198,2
37998,168,6,2026,2026m06,28,5,Rio Claro,3304409,Interior,0,...,0.0,0.0,4,0,0,0,0,0,32,2

In [ ]:
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37999 entries, 0 to 37998
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37999 non-null  int64
 1   mes                         37999 non-null  int64
 2   ano                         37999 non-null  int64
 3   mes_ano                     37999 non-null  str
 4   aisp                        37999 non-null  int64
 5   risp                        37999 non-null  int64
 6   munic                       37999 non-null  str
 7   mcirc                       37999 non-null  int64
 8   regiao                      37999 non-null  str
 9   hom_doloso                  37999 non-null  int64
 10  lesao_corp_morte            37999 non-null  int64
 11  latrocinio                  37999 non-null  int64
 12  cvli                        37999 non-null  int64
 13  hom_por_interv_policial     37999 non-null  int64
 14  feminicidio                 2877 non-null   float64
 15  letalidade_violenta         37999 non-null  int64
 16  tentat_hom                  37999 non-null  int64
 17  tentativa_feminicidio       2877 non-null   float64
 18  lesao_corp_dolosa           37999 non-null  int64
 19  estupro                     37999 non-null  int64
 20  hom_culposo                 37999 non-null  int64
 21  lesao_corp_culposa          37999 non-null  int64
 22  roubo_transeunte            37999 non-null  int64
 23  roubo_celular               37999 non-null  int64
 24  roubo_em_coletivo           37999 non-null  int64
 25  roubo_rua                   37999 non-null  int64
 26  roubo_veiculo               37999 non-null  int64
 27  roubo_carga                 37999 non-null  int64
 28  roubo_comercio              37999 non-null  int64
 29  roubo_residencia            37999 non-null  int64
 30  roubo_banco                 37999 non-null  int64
 31  roubo_cx_eletronico         37980 non-null  float64
 32  roubo_conducao_saque        37999 non-null  int64
 33  roubo_apos_saque            37999 non-null  int64
 34  roubo_bicicleta             20610 non-null  float64
 35  outros_roubos               37999 non-null  int64
 36  total_roubos                37999 non-null  int64
 37  furto_veiculos              37999 non-null  int64
 38  furto_transeunte            37999 non-null  int64
 39  furto_coletivo              37999 non-null  int64
 40  furto_celular               37999 non-null  int64
 41  furto_bicicleta             20610 non-null  float64
 42  outros_furtos               37999 non-null  int64
 43  total_furtos                37999 non-null  int64
 44  sequestro                   37999 non-null  int64
 45  extorsao                    37999 non-null  int64
 46  sequestro_relampago         37999 non-null  int64
 47  estelionato                 37999 non-null  int64
 48  apreensao_drogas            37999 non-null  int64
 49  posse_drogas                33353 non-null  float64
 50  trafico_drogas              33353 non-null  float64
 51  apreensao_drogas_sem_autor  33353 non-null  float64
 52  recuperacao_veiculos        37999 non-null  int64
 53  apf                         33353 non-null  float64
 54  aaapai                      33353 non-null  float64
 55  cmp                         33353 non-null  float64
 56  cmba                        33353 non-null  float64
 57  ameaca                      37999 non-null  int64
 58  pessoas_desaparecidas       37999 non-null  int64
 59  encontro_cadaver            37999 non-null  int64
 60  encontro_ossada             37999 non-null  int64
 61  pol_militares_mortos_serv   37999 non-null  int64
 62  pol_civis_mortos_serv       37999 non-null  int64
 63  registro_ocorrencias        37999 non-null  int64
 64  fase                        37999 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.8 MB

In [ ]:
df.head(2)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3

In [ ]:
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp = df_furto_cel_dp.sort_values(by='furto_celular', ascending = False)
df_furto_cel_dp

In [63]:
df_roubo_rua_dp = df.groupby('cisp')['roubo_rua'].sum().reset_index()
df_roubo_rua_dp = df_roubo_rua_dp.sort_values(by='roubo_rua', ascending = False)
df_roubo_rua_dp

     cisp  roubo_rua
52     59      87859
57     64      64737
30     34      58326
25     29      50126
65     74      47594
..    ...        ...
131   157         16
130   156         11
94    111          7
77     92          6
129   155          5

[138 rows x 2 columns]

In [64]:
array_roubo_rua_dp = np.array(df_roubo_rua_dp['roubo_rua'])

In [65]:

media = np.mean(array_roubo_rua_dp)
mediana = np.median(array_roubo_rua_dp)
q1 = np.percentile(array_roubo_rua_dp, 25)
q2 = np.percentile(array_roubo_rua_dp, 50)
q3 = np.percentile(array_roubo_rua_dp,75)

In [68]:
print (f'Média {media}\nMediana {mediana}\nQ1 {q1}\nQ2 {q2}\nQ3 {q3}')

Média 13035.13768115942
Mediana 5333.5
Q1 252.75
Q2 5333.5
Q3 23408.75
1.4440119398442712
144.40%

In [69]:
distancia = (media - mediana) / mediana
print(distancia)
print(f'{distancia:.2%}')

1.4440119398442712
144.40%

In [ ]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp = df_aaapai_dp.sort_values(by='aaapai', ascending = False)
df_aaapai_dp

In [ ]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False)
df_roubo_veiculo_dp

In [ ]:
df_capital = df[df['munic'] == 'Rio de Janeiro'] #usando sistema de filtro, assim seria na unha. dfdentro de munic só quero rio de janeiro
df_capital

In [ ]:
df_capital = df.loc[df['munic'] == 'Rio de Janeiro']

#usando .query() - sintaxw alternativa mais legível
df_capital = df.query("munic == 'Rio de Janeiro'")

df_furto_cel_dp_capital = df_capital.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp_capital = df_furto_cel_dp_capital.sort_values(by='furto_celular', ascending=False)
df_furto_cel_dp_capital

In [ ]:
munic_pedido = ['Belford Roxo', 'Nova Iguaçu', 'Queimados']

df_bel_nov_quei = df.loc[df["munic"].isin(munic_pedido) & (df['ano'] == 2025)] #fez a lista com munícipio para filtar eses 3 munic data frame.locdf procurar em munic dentro de munic pedido isin, dentro de, & add filtro ano.

df_furto_cel_dp_belford = df_bel_nov_quei.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp_belford = df_furto_cel_dp_belford.sort_values(by='furto_celular', ascending=False)
df_furto_cel_dp_belford

In [ ]:
array_furto_cel_dp = np.array(df_furto_cel_dp['furto_celular'])
array_furto_cel_dp

In [26]:
media = np.mean(array_furto_cel_dp)
mediana = np.median(array_furto_cel_dp)
q1 = np.percentile(array_furto_cel_dp, 25)
q2 = np.percentile(array_furto_cel_dp, 50)
q3 = np.percentile(array_furto_cel_dp,75)

In [ ]:
print(f'Media {media}')
print(f'Mediana {mediana}')
print(f'Q1: {q1}')
print(f'Q2: {q2}')
print(f'Q3: {q3}')

In [ ]:
df_furto_cel_acima_q3 = df_furto_cel_dp.loc[df_furto_cel_dp['furto_celular'] > q3]
df_furto_cel_acima_q3

In [ ]:
df_roubo_veiculo_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veiculo_dp = df_roubo_veiculo_dp.sort_values(by='roubo_veiculo', ascending = False)
df_roubo_veiculo_dp

In [ ]:
array_roubo_veiculo_dp = np.array(df_roubo_veiculo_dp['roubo_veiculo'])
array_furto_cel_dp

In [33]:
media = np.mean(array_roubo_veiculo_dp)
mediana = np.median(array_roubo_veiculo_dp)
q1 = np.percentile(array_roubo_veiculo_dp, 25)
q2 = np.percentile(array_roubo_veiculo_dp, 50)
q3 = np.percentile(array_roubo_veiculo_dp, 75)

In [ ]:
print (f'Média {media}\nMediana {mediana}\nQ1 {q1}\nQ2 {q2}\nQ3 {q3}')

In [ ]:
df_roubo_veiculo_dp_q3_acima = df_roubo_veiculo_dp.loc[df_roubo_veiculo_dp ['roubo_veiculo'] > q3]
df_roubo_veiculo_dp_q3_acima

In [ ]:
print(f'Média roubo {media}\nMediana roubo {mediana}')

In [ ]:
distancia = (media - mediana) / mediana
print(distancia)
print(f'{distancia:.2%}')

In [ ]:
df_aaapai_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_aaapai_dp = df_aaapai_dp.sort_values(by='aaapai', ascending = False)
df_aaapai_dp

In [ ]:
array_aaapai_dp = np.array(df_aaapai_dp['aaapai'])
array_aaapai_dp

In [61]:
media = np.mean(array_aaapai_dp)
mediana = np.median(array_aaapai_dp)
q1 = np.percentile(array_aaapai_dp, 25)
q2 = np.percentile(array_aaapai_dp, 50)
q3 = np.percentile(array_aaapai_dp, 75)
print (f'Média {media}\nMediana {mediana}\nQ1 {q1}\nQ2 {q2}\nQ3 {q3}')

Média 909.268115942029
Mediana 686.5
Q1 223.5
Q2 686.5
Q3 1275.75

In [62]:
distancia = (media - mediana) / mediana
print(distancia)
print(f'{distancia:.2%}')

0.3244983480583088
32.45%